import type { CatalogIndex } from '../data/catalog';
import type { Edge } from '../types';
import type { FlowLayout } from './flow';

// Renders a node set + edge list into Mermaid `flowchart` source. Pure (no DOM,
// no React) so it can be unit-tested in isolation. Edge style encodes the
// relationship — critical = thick (==>), external = dotted (-.->), otherwise
// solid (-->); node fill/stroke encodes criticality tier, mirroring the app.

const TIER_CLASS: Record<string, string> = { '0': 'tier0', '1': 'tier1', '2': 'tier2', '3': 'tier3' };

// Dark chips with tier-colored strokes — matches the Observatory aesthetic and
// reads well in mermaid.live / GitHub (dark boxes on a light canvas).
const CLASS_DEF: Record<string, string> = {
  tier0: 'fill:#3a121a,stroke:#FF4D5E,color:#ffd9dd,stroke-width:2px',
  tier1: 'fill:#3a2410,stroke:#FF9F45,color:#ffe6cc,stroke-width:2px',
  tier2: 'fill:#0f2742,stroke:#519EE6,color:#d6ebff,stroke-width:2px',
  tier3: 'fill:#0f3328,stroke:#4FD6A0,color:#cdf5e6,stroke-width:2px',
  tierU: 'fill:#23262e,stroke:#838795,color:#dfe4ec,stroke-width:2px',
  ext: 'fill:#241a38,stroke:#9F7BD6,color:#e9ddff,stroke-width:2px,stroke-dasharray:5 3',
};

export interface MermaidOptions {
  /** One id (single-root map) — kept for back-compat; prefer rootIds. */
  rootId?: string;
  /** Highlight a whole set of roots (multi-root map). */
  rootIds?: string[];
  title?: string;
  direction?: 'LR' | 'TB';
}

/** Sanitize a serviceId into a Mermaid-safe node identifier. */
const nodeKey = (id: string) => 's_' + id.replace(/[^a-zA-Z0-9_]/g, '_');

/** Escape characters that would break a Mermaid quoted label. */
const escapeLabel = (s: string) => s.replace(/"/g, '#quot;').replace(/[<>]/g, (c) => (c === '<' ? '#lt;' : '#gt;'));

export function toMermaid(
  index: CatalogIndex,
  nodeIds: Iterable<string>,
  edges: Edge[],
  opts: MermaidOptions = {},
): string {
  const dir = opts.direction ?? 'LR';
  const ids = [...new Set(nodeIds)];
  const lines: string[] = [];

  if (opts.title) lines.push(`%% ${opts.title}`);
  lines.push('%% Generated by Service Observatory');
  lines.push(`flowchart ${dir}`);

  // Group nodes by the class they'll use, and emit declarations.
  const byClass = new Map<string, string[]>();
  for (const id of ids) {
    const node = index.node(id);
    const key = nodeKey(id);
    let cls: string;
    let label: string;
    if (node?.kind === 'service') {
      const s = node.service;
      cls = TIER_CLASS[String(s.criticalityTier)] ?? 'tierU';
      label = `${escapeLabel(s.name)}<br/><small>${escapeLabel(s.serviceId)} · T${s.criticalityTier}</small>`;
    } else {
      cls = 'ext';
      const name = node?.kind === 'external' ? node.ext.name : id;
      label = `${escapeLabel(name)} ↗<br/><small>external</small>`;
    }
    lines.push(`  ${key}["${label}"]`);
    const arr = byClass.get(cls) ?? [];
    arr.push(key);
    byClass.set(cls, arr);
  }

  lines.push('');
  for (const e of edges) {
    const arrow = e.dep.critical ? '==>' : e.dep.external ? '-.->' : '-->';
    lines.push(`  ${nodeKey(e.from)} ${arrow}|${escapeLabel(e.dep.interaction)}| ${nodeKey(e.to)}`);
  }

  lines.push('');
  for (const [cls, members] of byClass) {
    lines.push(`  classDef ${cls} ${CLASS_DEF[cls]};`);
    lines.push(`  class ${members.join(',')} ${cls};`);
  }

  // Make the focal service(s) unmistakable (bright thick stroke over tier fill).
  const idSet = new Set(ids);
  const roots = opts.rootIds ?? (opts.rootId ? [opts.rootId] : []);
  for (const rid of roots) {
    if (idSet.has(rid)) lines.push(`  style ${nodeKey(rid)} stroke:#8ecbff,stroke-width:4px;`);
  }

  return lines.join('\n');
}

/** Mermaid `sankey-beta` rows from a FlowLayout. Mermaid sankey is CSV-bodied:
 *  one `source,target,value` line per link. Ghost targets get a "(loop)" label
 *  so the re-entry reads clearly. Labels are sanitized (commas/quotes stripped).
 *  Uses realId as the row identifier so external node ids are preserved verbatim. */
export function toMermaidSankey(layout: FlowLayout): string {
  const labelOf = new Map(layout.nodes.map((n) => [n.id, n.isGhost ? `${n.realId} (loop)` : n.realId]));
  const clean = (s: string) => s.replace(/[",]/g, ' ').trim();
  const rows = layout.links.map((l) => {
    const src = clean(labelOf.get(l.source) ?? l.source);
    const tgt = clean(labelOf.get(l.target) ?? l.target);
    return `${src},${tgt},${l.weight}`;
  });
  return ['sankey-beta', '', ...rows].join('\n');
}
