#!/usr/bin/env python3
"""Generate 50 simulated service catalog entries for visualization testing."""

import json
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "data")

# Demo regions per provider. Each service picks a stable index by serviceId so
# the Region facet/dimension has variety across the catalog.
_REGIONS = {
    "aws": ["us-east-1", "us-west-2", "eu-west-1"],
    "azure": ["eastus", "westeurope"],
    "on-prem": ["dc-atlanta", "dc-denver"],
}

def _region_for(provider, seed):
    opts = _REGIONS.get(provider)
    return opts[seed % len(opts)] if opts else None

def svc(service_id, name, team, team_email, lifecycle, tier, runtime, framework,
        product, value_stream, description, data_class, deps=None,
        resources=None, datastores=None, features=None, tags=None):
    obj = {
        "$schema": "https://service-catalog.internal/schemas/service-catalog.schema.json",
        "serviceId": service_id,
        "name": name,
        "description": description,
        "lifecycle": lifecycle,
        "criticalityTier": tier,
        "repository": f"https://github.com/acme/{service_id}",
        "provisionerRepoURL": f"https://github.com/acme/{service_id}-provisioner",
        "runtime": runtime,
        "softwareFramework": framework,
        "team": team,
        "teamEmail": team_email,
        "product": product,
        "valueStream": value_stream,
        "dataClassification": data_class,
    }
    if deps:
        obj["dependencies"] = deps
    if resources:
        seed = sum(ord(c) for c in service_id)
        for r in resources:
            if isinstance(r, dict) and "region" not in r:
                reg = _region_for(r.get("provider"), seed)
                if reg:
                    r["region"] = reg
        obj["resources"] = resources
    if datastores:
        obj["datastores"] = datastores
    if features:
        obj["features"] = features
    if tags:
        obj["tags"] = tags
    return obj

def dep(service_id, interaction, critical, purpose, external=False, endpoint=None):
    d = {"serviceId": service_id, "interaction": interaction, "critical": critical,
         "purpose": purpose, "external": external}
    if endpoint:
        d["endpoint"] = endpoint
    return d

def rds(name, engine="postgres", critical=True, restricted=False):
    return {"name": name, "type": "RDS", "restrictedData": restricted,
            "critical": critical, "retention": "P7Y",
            "engine": engine, "version": "15", "drStrategy": "startWithReplicatedData"}

def dynamo(name, critical=False):
    return {"name": name, "type": "DynamoDB", "restrictedData": False,
            "critical": critical, "retention": "P90D", "drStrategy": "activeActive"}

def s3(name, restricted=False):
    return {"name": name, "type": "S3", "restrictedData": restricted,
            "critical": False, "retention": "P7Y", "drStrategy": "activeActive"}

def elasticache(name):
    return {"name": name, "type": "ElastiCache", "restrictedData": False,
            "critical": False, "retention": "P0D", "drStrategy": "startEmpty"}

SERVICES = [

    # ── LEAVES (no dependencies) ──────────────────────────────────────────────

    svc("auth-service", "Auth Service", "platform", "platform@acme.com",
        "prod", 0, "Java 21", "spring-boot",
        "Platform", "Core Infrastructure",
        "Central authentication and token issuance for all services.",
        "CONFIDENTIAL",
        resources=[{"provider": "aws", "type": "RDS", "purpose": "Token store", "engine": "postgres",
                    "version": "15", "drStrategy": "activeActive"},
                   {"provider": "aws", "type": "ElastiCache", "purpose": "Session cache", "drStrategy": "startEmpty"}],
        datastores=[rds("auth-db", critical=True, restricted=True)],
        features=[{"name": "oauth2", "description": "OAuth 2.0 / OIDC flows"},
                  {"name": "mfa", "description": "Multi-factor authentication"},
                  {"name": "service-accounts", "description": "M2M service account tokens"}],
        tags={"tier": "0", "domain": "security"}),

    svc("config-service", "Config Service", "platform", "platform@acme.com",
        "prod", 1, "Go 1.22", "chi",
        "Platform", "Core Infrastructure",
        "Centralised runtime configuration and feature flag distribution.",
        "INTERNAL",
        resources=[{"provider": "azure", "type": "azure-cosmos-db", "purpose": "Config store", "drStrategy": "activeActive"},
                   {"provider": "azure", "type": "azure-blob-storage", "purpose": "Config snapshots", "drStrategy": "activeActive"}],
        datastores=[dynamo("config-store")],
        features=[{"name": "hot-reload"}, {"name": "env-scoping"}],
        tags={"tier": "1", "domain": "platform"}),

    svc("event-bus-service", "Event Bus Service", "platform", "platform@acme.com",
        "prod", 0, "Java 21", "spring-boot",
        "Platform", "Core Infrastructure",
        "Managed async event routing over SNS/SQS.",
        "INTERNAL",
        resources=[{"provider": "aws", "type": "SNS", "purpose": "Topic fanout", "drStrategy": "activeActive"},
                   {"provider": "aws", "type": "SQS", "purpose": "Message queuing", "drStrategy": "activeActive"}],
        features=[{"name": "dead-letter-queue"}, {"name": "schema-registry"}],
        tags={"tier": "0", "domain": "messaging"}),

    svc("storage-service", "Storage Service", "platform", "platform@acme.com",
        "prod", 1, "Python 3.12", "fastapi",
        "Platform", "Core Infrastructure",
        "Managed object storage with access control and virus scanning.",
        "INTERNAL",
        resources=[{"provider": "aws", "type": "S3", "purpose": "Document storage", "drStrategy": "activeActive"},
                   {"provider": "aws", "type": "Lambda", "purpose": "Virus scan on upload", "drStrategy": "none"}],
        features=[{"name": "presigned-urls"}, {"name": "virus-scanning"}],
        tags={"tier": "1", "domain": "storage"}),

    svc("secrets-service", "Secrets Service", "platform", "platform@acme.com",
        "prod", 0, "Go 1.22", "chi",
        "Platform", "Core Infrastructure",
        "Secret rotation and distribution backed by AWS Secrets Manager.",
        "RESTRICTED",
        resources=[{"provider": "aws", "type": "SecretsManager", "purpose": "Secret storage", "drStrategy": "activeActive"}],
        tags={"tier": "0", "domain": "security"}),

    svc("audit-log-service", "Audit Log Service", "platform", "platform@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Platform", "Compliance",
        "Immutable append-only audit trail for all user and system actions.",
        "RESTRICTED",
        resources=[{"provider": "aws", "type": "Kinesis", "purpose": "Audit event stream", "drStrategy": "activeActive"},
                   {"provider": "aws", "type": "S3", "purpose": "Long-term audit archive", "drStrategy": "activeActive"}],
        datastores=[rds("audit-db", critical=True, restricted=True)],
        features=[{"name": "immutable-records"}, {"name": "hipaa-export"}],
        tags={"tier": "1", "domain": "compliance"}),

    svc("notification-service", "Notification Service", "platform", "platform@acme.com",
        "prod", 1, "Python 3.12", "fastapi",
        "Platform", "Core Infrastructure",
        "Multi-channel notification dispatch: email, SMS, push.",
        "CONFIDENTIAL",
        resources=[{"provider": "aws", "type": "SES", "purpose": "Email delivery", "drStrategy": "none"},
                   {"provider": "aws", "type": "SNS", "purpose": "SMS and push", "drStrategy": "none"},
                   {"provider": "aws", "type": "SQS", "purpose": "Outbound queue", "drStrategy": "activeActive"}],
        features=[{"name": "templating"}, {"name": "delivery-tracking"}, {"name": "opt-out"}],
        tags={"tier": "1", "domain": "comms"}),

    # ── TIER 1 (depend only on leaves) ───────────────────────────────────────

    svc("user-service", "User Service", "identity", "identity@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Identity", "Member Engagement",
        "User profile management and preferences.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("audit-log-service", "async-event", False, "Profile change audit"),
              dep("notification-service", "async-event", False, "Welcome and alert emails")],
        datastores=[rds("user-db", critical=True, restricted=True)],
        features=[{"name": "profile-management"}, {"name": "preferences"}, {"name": "mfa-enrollment"}],
        tags={"tier": "1", "domain": "identity"}),

    svc("payment-gateway", "Payment Gateway", "billing", "billing@acme.com",
        "prod", 0, "Java 21", "spring-boot",
        "Billing", "Revenue",
        "PCI-scoped payment processing against external processors.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("secrets-service", "sync-http", True, "Processor credentials"),
              dep("audit-log-service", "async-event", True, "Payment audit trail"),
              dep("stripe", "sync-http", True, "Card processing", external=True, endpoint="https://api.stripe.com")],
        datastores=[rds("payment-db", critical=True, restricted=True)],
        features=[{"name": "card-tokenization"}, {"name": "refunds"}, {"name": "disputes"}],
        tags={"tier": "0", "domain": "billing", "pci": "true"}),

    svc("product-catalog-service", "Product Catalog Service", "commerce", "commerce@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Commerce", "Member Engagement",
        "Health plan and product catalog with eligibility rules.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("config-service", "sync-http", False, "Feature flags"),
              dep("storage-service", "s3", False, "Product images and documents")],
        datastores=[rds("catalog-db"), dynamo("catalog-cache")],
        features=[{"name": "product-search"}, {"name": "eligibility-rules"}, {"name": "plan-comparison"}],
        tags={"tier": "2", "domain": "commerce"}),

    svc("sso-service", "SSO Service", "identity", "identity@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Identity", "Core Infrastructure",
        "SAML/OIDC federation broker for enterprise customers.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Upstream token exchange"),
              dep("secrets-service", "sync-http", True, "SAML signing keys"),
              dep("audit-log-service", "async-event", False, "Federation audit")],
        datastores=[rds("sso-db", critical=True, restricted=True)],
        features=[{"name": "saml2"}, {"name": "oidc"}, {"name": "jit-provisioning"}],
        tags={"tier": "1", "domain": "identity"}),

    svc("provider-directory", "Provider Directory", "clinical", "clinical@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Clinical", "Care Navigation",
        "Searchable directory of in-network providers and facilities.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("config-service", "sync-http", False, "Search config"),
              dep("storage-service", "s3", False, "Provider headshots and docs")],
        datastores=[rds("provider-db"), {"name": "provider-search", "type": "OpenSearch",
                                          "restrictedData": False, "critical": False, "retention": "P1Y",
                                          "drStrategy": "startWithReplicatedData"}],
        features=[{"name": "geo-search"}, {"name": "specialty-filter"}, {"name": "accepting-patients"}],
        tags={"tier": "2", "domain": "clinical"}),

    svc("cache-service", "Cache Service", "platform", "platform@acme.com",
        "prod", 2, "Go 1.22", "chi",
        "Platform", "Core Infrastructure",
        "Shared distributed cache layer backed by ElastiCache.",
        "INTERNAL",
        deps=[dep("config-service", "sync-http", False, "TTL and eviction config")],
        resources=[{"provider": "on-prem", "type": "vm", "purpose": "Redis cluster", "instanceType": "16c/64g", "drStrategy": "startEmpty"}],
        tags={"tier": "2", "domain": "platform"}),

    # ── TIER 2 ───────────────────────────────────────────────────────────────

    svc("inventory-service", "Inventory Service", "commerce", "commerce@acme.com",
        "prod", 2, "Java 21", "spring-boot",
        "Commerce", "Supply Chain",
        "Real-time inventory tracking and reservation.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("product-catalog-service", "sync-http", True, "Product lookup"),
              dep("event-bus-service", "async-event", True, "Inventory change events")],
        datastores=[rds("inventory-db", critical=True)],
        features=[{"name": "soft-reservation"}, {"name": "reorder-alerts"}],
        tags={"tier": "2", "domain": "commerce"}),

    svc("pricing-service", "Pricing Service", "commerce", "commerce@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Commerce", "Revenue",
        "Dynamic pricing engine with plan-specific rules.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("product-catalog-service", "sync-http", True, "Product attributes"),
              dep("config-service", "sync-http", False, "Pricing rules"),
              dep("cache-service", "sync-http", False, "Price cache")],
        datastores=[rds("pricing-db")],
        features=[{"name": "bulk-pricing"}, {"name": "promo-codes"}],
        tags={"tier": "2", "domain": "commerce"}),

    svc("billing-service", "Billing Service", "billing", "billing@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Billing", "Revenue",
        "Premium billing, invoicing, and payment scheduling.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("payment-gateway", "sync-http", True, "Payment execution"),
              dep("notification-service", "async-event", False, "Invoice and receipt emails"),
              dep("audit-log-service", "async-event", True, "Billing audit trail")],
        datastores=[rds("billing-db", critical=True, restricted=True)],
        features=[{"name": "invoicing"}, {"name": "autopay"}, {"name": "payment-history"}],
        tags={"tier": "1", "domain": "billing"}),

    svc("search-service", "Search Service", "commerce", "commerce@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Commerce", "Member Engagement",
        "Full-text search across plans, providers, and documents.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("product-catalog-service", "sync-http", False, "Index source"),
              dep("provider-directory", "sync-http", False, "Provider index source"),
              dep("config-service", "sync-http", False, "Search tuning")],
        resources=[{"provider": "aws", "type": "OpenSearch", "purpose": "Search index", "drStrategy": "startWithReplicatedData"}],
        features=[{"name": "faceted-search"}, {"name": "spell-correction"}],
        tags={"tier": "2", "domain": "commerce"}),

    svc("rate-limiter", "Rate Limiter", "platform", "platform@acme.com",
        "prod", 1, "Go 1.22", "chi",
        "Platform", "Core Infrastructure",
        "Token bucket rate limiting for all inbound API traffic.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Principal identification"),
              dep("config-service", "sync-http", True, "Limit policies"),
              dep("cache-service", "sync-http", True, "Counter storage")],
        tags={"tier": "1", "domain": "platform"}),

    svc("claims-service", "Claims Service", "clinical", "clinical@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Clinical", "Revenue Cycle",
        "Claims ingestion, adjudication, and status tracking.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("user-service", "sync-http", True, "Member lookup"),
              dep("audit-log-service", "async-event", True, "Claims audit"),
              dep("event-bus-service", "async-event", True, "Claims status events")],
        datastores=[rds("claims-db", critical=True, restricted=True)],
        features=[{"name": "adjudication"}, {"name": "edi-835"}, {"name": "eob-generation"}],
        tags={"tier": "1", "domain": "clinical", "phi": "true"}),

    svc("member-service", "Member Service", "identity", "identity@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Identity", "Member Engagement",
        "Member enrollment, eligibility, and plan assignment.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("user-service", "sync-http", True, "User profile"),
              dep("audit-log-service", "async-event", True, "Enrollment audit"),
              dep("notification-service", "async-event", False, "Enrollment confirmation")],
        datastores=[rds("member-db", critical=True, restricted=True)],
        features=[{"name": "enrollment"}, {"name": "plan-assignment"}, {"name": "cobra"}],
        tags={"tier": "1", "domain": "identity", "phi": "true"}),

    svc("document-service", "Document Service", "platform", "platform@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Platform", "Member Engagement",
        "Document generation, storage, and retrieval.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("storage-service", "s3", True, "Document persistence"),
              dep("audit-log-service", "async-event", False, "Access audit")],
        datastores=[rds("document-meta-db"), s3("document-store", restricted=True)],
        features=[{"name": "pdf-generation"}, {"name": "e-signature"}, {"name": "template-engine"}],
        tags={"tier": "2", "domain": "platform"}),

    svc("identity-broker", "Identity Broker", "identity", "identity@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Identity", "Core Infrastructure",
        "Routes authentication to the correct IdP based on org routing rules.",
        "CONFIDENTIAL",
        deps=[dep("sso-service", "sync-http", True, "IdP federation"),
              dep("auth-service", "sync-http", True, "Downstream token issuance"),
              dep("audit-log-service", "async-event", True, "Auth routing audit"),
              dep("config-service", "sync-http", True, "Org routing config")],
        datastores=[rds("idbroker-db", critical=True, restricted=True)],
        features=[{"name": "org-routing"}, {"name": "step-up-auth"}, {"name": "device-trust"}],
        tags={"tier": "1", "domain": "identity"}),

    # ── TIER 3 ───────────────────────────────────────────────────────────────

    svc("raw-data-collector", "Raw Data Collector", "analytics", "analytics@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Analytics", "Data Platform",
        "Collects raw telemetry and business events from the event bus.",
        "INTERNAL",
        deps=[dep("event-bus-service", "async-event", True, "Event ingestion"),
              dep("auth-service", "sync-http", True, "Token validation"),
              dep("storage-service", "s3", True, "Raw event archive")],
        resources=[{"provider": "aws", "type": "Kinesis", "purpose": "Event stream ingestion", "drStrategy": "activeActive"},
                   {"provider": "aws", "type": "S3", "purpose": "Raw data lake", "drStrategy": "activeActive"}],
        tags={"tier": "2", "domain": "analytics"}),

    svc("cart-service", "Cart Service", "commerce", "commerce@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Commerce", "Member Engagement",
        "Shopping cart with real-time pricing and inventory checks.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("product-catalog-service", "sync-http", True, "Product details"),
              dep("inventory-service", "sync-http", True, "Availability check"),
              dep("pricing-service", "sync-http", True, "Live pricing"),
              dep("config-service", "sync-http", False, "Cart rules")],
        datastores=[dynamo("cart-store")],
        features=[{"name": "save-for-later"}, {"name": "cart-recovery"}, {"name": "coupon-application"}],
        tags={"tier": "2", "domain": "commerce"}),

    svc("eligibility-service", "Eligibility Service", "clinical", "clinical@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Clinical", "Revenue Cycle",
        "Real-time eligibility verification against payer sources.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("user-service", "sync-http", True, "Member lookup"),
              dep("claims-service", "sync-http", True, "Claims history"),
              dep("clearinghouse", "sync-http", True, "270/271 transactions", external=True)],
        datastores=[rds("eligibility-db", critical=True, restricted=True)],
        features=[{"name": "270-271"}, {"name": "real-time-verification"}, {"name": "batch-eligibility"}],
        tags={"tier": "1", "domain": "clinical", "phi": "true"}),

    svc("api-gateway", "API Gateway", "platform", "platform@acme.com",
        "prod", 0, "Go 1.22", "chi",
        "Platform", "Core Infrastructure",
        "Edge gateway: routing, auth enforcement, rate limiting, and TLS termination.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "JWT validation"),
              dep("rate-limiter", "sync-http", True, "Inbound rate limiting"),
              dep("config-service", "sync-http", True, "Route configuration"),
              dep("audit-log-service", "async-event", False, "Access logging")],
        features=[{"name": "jwt-validation"}, {"name": "route-matching"},
                  {"name": "tls-termination"}, {"name": "request-tracing"}],
        tags={"tier": "0", "domain": "platform"}),

    svc("monitoring-service", "Monitoring Service", "platform", "platform@acme.com",
        "prod", 1, "Python 3.12", "fastapi",
        "Platform", "Observability",
        "Metrics collection, anomaly detection, and SLO tracking.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("event-bus-service", "async-event", False, "Metric events"),
              dep("storage-service", "s3", False, "Metric snapshots")],
        resources=[{"provider": "azure", "type": "azure-monitor", "purpose": "Metrics and alarms", "drStrategy": "none"},
                   {"provider": "azure", "type": "azure-sql", "purpose": "Time-series storage", "drStrategy": "activeActive"}],
        features=[{"name": "slo-tracking"}, {"name": "anomaly-detection"}, {"name": "dashboards"}],
        tags={"tier": "1", "domain": "observability"}),

    svc("consent-service", "Consent Service", "identity", "identity@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Identity", "Compliance",
        "HIPAA authorization and consent record management.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("audit-log-service", "async-event", True, "Consent change audit"),
              dep("user-service", "sync-http", True, "Member identity"),
              dep("notification-service", "async-event", False, "Consent receipts")],
        datastores=[rds("consent-db", critical=True, restricted=True)],
        features=[{"name": "hipaa-auth"}, {"name": "revocation"}, {"name": "consent-history"}],
        tags={"tier": "1", "domain": "compliance", "phi": "true"}),

    svc("formulary-service", "Formulary Service", "clinical", "clinical@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Clinical", "Care Navigation",
        "Drug formulary lookup and tier classification by plan.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("config-service", "sync-http", False, "Formulary rules"),
              dep("product-catalog-service", "sync-http", True, "Plan association")],
        datastores=[rds("formulary-db")],
        features=[{"name": "drug-search"}, {"name": "tier-lookup"}, {"name": "pa-requirements"}],
        tags={"tier": "2", "domain": "clinical"}),

    svc("feature-flag-service", "Feature Flag Service", "platform", "platform@acme.com",
        "prod", 2, "Go 1.22", "chi",
        "Platform", "Core Infrastructure",
        "Runtime feature flags with targeting rules and gradual rollout.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("config-service", "sync-http", True, "Flag definitions")],
        datastores=[dynamo("flag-store")],
        features=[{"name": "percentage-rollout"}, {"name": "user-targeting"}, {"name": "kill-switch"}],
        tags={"tier": "2", "domain": "platform"}),

    # ── TIER 4 ───────────────────────────────────────────────────────────────

    svc("etl-service", "ETL Service", "analytics", "analytics@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Analytics", "Data Platform",
        "Transforms and loads raw events into the analytics warehouse.",
        "INTERNAL",
        deps=[dep("raw-data-collector", "s3", True, "Raw event source"),
              dep("auth-service", "sync-http", True, "Token validation"),
              dep("storage-service", "s3", True, "Staging area"),
              dep("event-bus-service", "async-event", False, "ETL job status events")],
        resources=[{"provider": "aws", "type": "Glue", "purpose": "Spark ETL jobs", "drStrategy": "none"},
                   {"provider": "aws", "type": "S3", "purpose": "Transformed data", "drStrategy": "activeActive"}],
        tags={"tier": "2", "domain": "analytics"}),

    svc("order-validation-service", "Order Validation Service", "commerce", "commerce@acme.com",
        "prod", 2, "Java 21", "spring-boot",
        "Commerce", "Member Engagement",
        "Validates orders for eligibility, inventory, and compliance.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("cart-service", "sync-http", True, "Cart contents"),
              dep("inventory-service", "sync-http", True, "Stock confirmation"),
              dep("eligibility-service", "sync-http", True, "Member eligibility")],
        features=[{"name": "eligibility-check"}, {"name": "fraud-screening"}],
        tags={"tier": "2", "domain": "commerce"}),

    svc("prior-auth-service", "Prior Authorization Service", "clinical", "clinical@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Clinical", "Revenue Cycle",
        "Prior authorization request submission and decision management.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("eligibility-service", "sync-http", True, "Member eligibility"),
              dep("claims-service", "sync-http", True, "Claims context"),
              dep("notification-service", "async-event", False, "PA decision notifications"),
              dep("audit-log-service", "async-event", True, "PA audit trail")],
        datastores=[rds("prior-auth-db", critical=True, restricted=True)],
        features=[{"name": "278-transaction"}, {"name": "criteria-engine"}, {"name": "peer-review"}],
        tags={"tier": "1", "domain": "clinical", "phi": "true"}),

    svc("patient-portal", "Patient Portal BFF", "member-experience", "mx@acme.com",
        "prod", 1, "Python 3.12", "fastapi",
        "Member Experience", "Member Engagement",
        "Backend-for-frontend for the member-facing web and mobile portal.",
        "CONFIDENTIAL",
        deps=[dep("identity-broker", "sync-http", True, "Authentication"),
              dep("auth-service", "sync-http", True, "Token refresh"),
              dep("user-service", "sync-http", True, "Profile data"),
              dep("notification-service", "async-event", False, "In-app notifications")],
        features=[{"name": "session-management"}, {"name": "graphql-gateway"}, {"name": "push-notifications"}],
        tags={"tier": "1", "domain": "member-experience"}),

    svc("alerting-service", "Alerting Service", "platform", "platform@acme.com",
        "prod", 1, "Python 3.12", "fastapi",
        "Platform", "Observability",
        "Threshold-based alerts with escalation routing.",
        "INTERNAL",
        deps=[dep("monitoring-service", "sync-http", True, "Metric thresholds"),
              dep("auth-service", "sync-http", True, "Token validation"),
              dep("notification-service", "async-event", True, "Alert dispatch"),
              dep("config-service", "sync-http", False, "Escalation policies")],
        features=[{"name": "pagerduty-integration"}, {"name": "silence-windows"}, {"name": "escalation"}],
        tags={"tier": "1", "domain": "observability"}),

    svc("data-masking-service", "Data Masking Service", "platform", "platform@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Platform", "Compliance",
        "Masks and tokenizes PHI/PII before non-production distribution.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("consent-service", "sync-http", True, "Consent verification"),
              dep("audit-log-service", "async-event", True, "Masking audit")],
        features=[{"name": "phi-tokenization"}, {"name": "de-identification"}, {"name": "safe-harbor"}],
        tags={"tier": "1", "domain": "compliance", "phi": "true"}),

    svc("appointment-service", "Appointment Service", "clinical", "clinical@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Clinical", "Care Navigation",
        "Appointment scheduling and calendar management.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("user-service", "sync-http", True, "Member profile"),
              dep("notification-service", "async-event", False, "Reminders"),
              dep("provider-directory", "sync-http", True, "Provider availability"),
              dep("audit-log-service", "async-event", False, "Appointment audit")],
        datastores=[rds("appointment-db", critical=True, restricted=True)],
        features=[{"name": "online-scheduling"}, {"name": "waitlist"}, {"name": "cancellation-policy"}],
        tags={"tier": "2", "domain": "clinical", "phi": "true"}),

    # ── TIER 5 ───────────────────────────────────────────────────────────────

    svc("data-warehouse", "Data Warehouse", "analytics", "analytics@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Analytics", "Data Platform",
        "Columnar analytics warehouse for BI and reporting.",
        "INTERNAL",
        deps=[dep("etl-service", "s3", True, "Transformed data load"),
              dep("auth-service", "sync-http", True, "Token validation"),
              dep("config-service", "sync-http", False, "Schema registry config")],
        resources=[{"provider": "azure", "type": "azure-synapse", "purpose": "Columnar analytics store", "drStrategy": "startWithReplicatedData"}],
        features=[{"name": "dbt-transforms"}, {"name": "query-governance"}, {"name": "data-lineage"}],
        tags={"tier": "2", "domain": "analytics"}),

    svc("order-processing-service", "Order Processing Service", "commerce", "commerce@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Commerce", "Member Engagement",
        "Orchestrates payment, fulfillment, and notification for confirmed orders.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("order-validation-service", "sync-http", True, "Pre-flight validation"),
              dep("payment-gateway", "sync-http", True, "Payment capture"),
              dep("notification-service", "async-event", False, "Order confirmation"),
              dep("event-bus-service", "async-event", True, "Order placed event")],
        datastores=[rds("order-db", critical=True, restricted=True)],
        features=[{"name": "saga-orchestration"}, {"name": "idempotent-processing"}, {"name": "cancellation"}],
        tags={"tier": "1", "domain": "commerce"}),

    svc("care-management-service", "Care Management Service", "clinical", "clinical@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Clinical", "Care Navigation",
        "Care plan creation, gap-in-care identification, and case management.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("member-service", "sync-http", True, "Member enrollment status"),
              dep("claims-service", "sync-http", True, "Claims-based gap analysis"),
              dep("prior-auth-service", "sync-http", True, "PA status"),
              dep("notification-service", "async-event", False, "Care gap outreach")],
        datastores=[rds("care-plan-db", critical=True, restricted=True)],
        features=[{"name": "care-plan-builder"}, {"name": "gap-in-care"}, {"name": "case-assignment"}],
        tags={"tier": "1", "domain": "clinical", "phi": "true"}),

    svc("api-aggregator", "API Aggregator", "member-experience", "mx@acme.com",
        "prod", 1, "Python 3.12", "fastapi",
        "Member Experience", "Member Engagement",
        "Aggregates data from multiple domain services for the portal.",
        "CONFIDENTIAL",
        deps=[dep("patient-portal", "sync-http", True, "Session context"),
              dep("auth-service", "sync-http", True, "Token validation"),
              dep("config-service", "sync-http", False, "Aggregation config"),
              dep("search-service", "sync-http", False, "Unified search")],
        features=[{"name": "response-aggregation"}, {"name": "caching-layer"}, {"name": "schema-stitching"}],
        tags={"tier": "1", "domain": "member-experience"}),

    # ── TIER 6 ───────────────────────────────────────────────────────────────

    svc("analytics-service", "Analytics Service", "analytics", "analytics@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Analytics", "Data Platform",
        "Self-service analytics API exposing warehouse queries to internal tools.",
        "INTERNAL",
        deps=[dep("data-warehouse", "sync-http", True, "Query execution"),
              dep("auth-service", "sync-http", True, "Token validation"),
              dep("config-service", "sync-http", False, "Query governance rules"),
              dep("cache-service", "sync-http", False, "Query result cache")],
        features=[{"name": "saved-queries"}, {"name": "scheduled-reports"}, {"name": "data-export"}],
        tags={"tier": "2", "domain": "analytics"}),

    svc("order-fulfillment-service", "Order Fulfillment Service", "commerce", "commerce@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Commerce", "Member Engagement",
        "Fulfillment orchestration: provisioning, shipping, and confirmation.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("order-processing-service", "sync-http", True, "Confirmed order data"),
              dep("inventory-service", "sync-http", True, "Stock deduction"),
              dep("notification-service", "async-event", False, "Fulfillment status updates"),
              dep("event-bus-service", "async-event", True, "Fulfillment events")],
        datastores=[rds("fulfillment-db", critical=True)],
        features=[{"name": "fulfillment-tracking"}, {"name": "backorder-management"}],
        tags={"tier": "1", "domain": "commerce"}),

    svc("mobile-api", "Mobile API Gateway", "member-experience", "mx@acme.com",
        "prod", 1, "Go 1.22", "chi",
        "Member Experience", "Member Engagement",
        "API gateway optimized for mobile clients: compression, offline sync.",
        "CONFIDENTIAL",
        deps=[dep("api-aggregator", "sync-http", True, "Backend aggregation"),
              dep("auth-service", "sync-http", True, "Token validation"),
              dep("notification-service", "async-event", False, "Push notifications"),
              dep("feature-flag-service", "sync-http", False, "Mobile feature flags")],
        features=[{"name": "response-compression"}, {"name": "offline-sync"}, {"name": "push-relay"}],
        tags={"tier": "1", "domain": "member-experience"}),

    svc("telemedicine-service", "Telemedicine Service", "clinical", "clinical@acme.com",
        "prod", 1, "Python 3.12", "fastapi",
        "Clinical", "Care Navigation",
        "Video visit orchestration and virtual waiting room.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("appointment-service", "sync-http", True, "Visit scheduling"),
              dep("user-service", "sync-http", True, "Member profile"),
              dep("notification-service", "async-event", False, "Visit reminders"),
              dep("twilio", "sync-http", True, "Video sessions", external=True)],
        datastores=[rds("telemedicine-db", critical=True, restricted=True)],
        features=[{"name": "virtual-waiting-room"}, {"name": "video-recording"}, {"name": "e-prescribe"}],
        tags={"tier": "1", "domain": "clinical", "phi": "true"}),

    # ── TIER 7 ───────────────────────────────────────────────────────────────

    svc("report-generator", "Report Generator", "analytics", "analytics@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Analytics", "Data Platform",
        "Generates regulatory and operational reports from the analytics layer.",
        "CONFIDENTIAL",
        deps=[dep("analytics-service", "sync-http", True, "Report data queries"),
              dep("auth-service", "sync-http", True, "Token validation"),
              dep("notification-service", "async-event", False, "Report-ready notifications"),
              dep("storage-service", "s3", True, "Report file storage")],
        datastores=[s3("report-archive")],
        features=[{"name": "pdf-export"}, {"name": "scheduled-delivery"}, {"name": "hipaa-5010"}],
        tags={"tier": "2", "domain": "analytics"}),

    svc("shipping-service", "Shipping Service", "commerce", "commerce@acme.com",
        "prod", 2, "Java 21", "spring-boot",
        "Commerce", "Supply Chain",
        "Label generation and carrier integration for physical shipments.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("order-fulfillment-service", "sync-http", True, "Fulfillment order data"),
              dep("notification-service", "async-event", False, "Tracking updates"),
              dep("ups", "sync-http", False, "Carrier API", external=True)],
        datastores=[rds("shipping-db")],
        features=[{"name": "label-generation"}, {"name": "tracking"}, {"name": "returns-label"}],
        tags={"tier": "2", "domain": "commerce"}),

    # ── REMAINING SERVICES ───────────────────────────────────────────────────

    svc("returns-service", "Returns Service", "commerce", "commerce@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Commerce", "Member Engagement",
        "Return merchandise authorization and refund processing.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("order-processing-service", "sync-http", True, "Original order lookup"),
              dep("inventory-service", "sync-http", True, "Stock replenishment"),
              dep("payment-gateway", "sync-http", True, "Refund processing")],
        datastores=[rds("returns-db")],
        features=[{"name": "rma-workflow"}, {"name": "restocking-rules"}],
        tags={"tier": "2", "domain": "commerce"}),

    svc("bulk-export-service", "Bulk Export Service", "analytics", "analytics@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Analytics", "Data Platform",
        "FHIR bulk export and large data extracts for external partners.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("data-masking-service", "sync-http", True, "PHI masking before export"),
              dep("storage-service", "s3", True, "Export staging"),
              dep("report-generator", "sync-http", False, "Report inclusion"),
              dep("audit-log-service", "async-event", True, "Export audit trail")],
        datastores=[s3("bulk-export-staging", restricted=True)],
        features=[{"name": "fhir-r4-bulk"}, {"name": "ndjson-export"}, {"name": "partner-delivery"}],
        tags={"tier": "2", "domain": "analytics", "phi": "true"}),

    svc("integration-hub", "Integration Hub", "platform", "platform@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Platform", "Core Infrastructure",
        "HL7, X12, and REST integration gateway for external payer and provider systems.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("api-gateway", "sync-http", True, "Inbound routing"),
              dep("event-bus-service", "async-event", True, "Inbound event publishing"),
              dep("notification-service", "async-event", False, "Integration alerts"),
              dep("audit-log-service", "async-event", True, "Transaction audit")],
        datastores=[rds("integration-db", critical=True, restricted=True)],
        features=[{"name": "hl7-v2"}, {"name": "x12-837"}, {"name": "fhir-r4"}, {"name": "partner-onboarding"}],
        tags={"tier": "1", "domain": "integration", "phi": "true"}),

    svc("provider-portal-bff", "Provider Portal BFF", "clinical", "clinical@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Clinical", "Care Navigation",
        "Backend-for-frontend for the provider-facing portal.",
        "CONFIDENTIAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("provider-directory", "sync-http", True, "Provider profile"),
              dep("claims-service", "sync-http", True, "Claims status"),
              dep("prior-auth-service", "sync-http", True, "PA requests"),
              dep("document-service", "sync-http", False, "Clinical documents")],
        features=[{"name": "claims-dashboard"}, {"name": "pa-submission"}, {"name": "remittance-view"}],
        tags={"tier": "2", "domain": "clinical"}),

    svc("risk-scoring-service", "Risk Scoring Service", "analytics", "analytics@acme.com",
        "prod", 1, "Python 3.12", "fastapi",
        "Analytics", "Care Navigation",
        "ML-based member risk stratification for care management prioritisation.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("analytics-service", "sync-http", True, "Feature data"),
              dep("member-service", "sync-http", True, "Member attributes"),
              dep("claims-service", "sync-http", True, "Claims features"),
              dep("audit-log-service", "async-event", True, "Scoring audit")],
        datastores=[rds("risk-scores-db", critical=True, restricted=True),
                    s3("model-artifacts")],
        features=[{"name": "hcc-coding"}, {"name": "readmission-risk"}, {"name": "model-versioning"}],
        tags={"tier": "1", "domain": "analytics", "phi": "true"}),

    svc("network-adequacy-service", "Network Adequacy Service", "clinical", "clinical@acme.com",
        "non-prod", 2, "Python 3.12", "fastapi",
        "Clinical", "Regulatory",
        "CMS network adequacy reporting and access-to-care calculations.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("provider-directory", "sync-http", True, "Provider roster"),
              dep("member-service", "sync-http", True, "Member geography"),
              dep("config-service", "sync-http", False, "Adequacy standards config"),
              dep("report-generator", "sync-http", False, "CMS report generation")],
        datastores=[rds("adequacy-db")],
        features=[{"name": "geo-calculations"}, {"name": "time-distance"}, {"name": "cms-reporting"}],
        tags={"tier": "2", "domain": "clinical", "regulatory": "true"}),

    svc("drug-interaction-service", "Drug Interaction Service", "clinical", "clinical@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Clinical", "Care Navigation",
        "Drug-drug and drug-condition interaction checking at point of care.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("formulary-service", "sync-http", True, "Drug data"),
              dep("first-databank", "sync-http", True, "Interaction database", external=True),
              dep("audit-log-service", "async-event", True, "Override audit")],
        datastores=[rds("drug-interaction-db", critical=True, restricted=True)],
        features=[{"name": "ddi-checking"}, {"name": "allergy-screening"}, {"name": "clinical-override"}],
        tags={"tier": "1", "domain": "clinical", "phi": "true"}),

    svc("population-health-service", "Population Health Service", "analytics", "analytics@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Analytics", "Care Navigation",
        "Population cohort analysis and public health reporting.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("risk-scoring-service", "sync-http", True, "Risk stratification"),
              dep("care-management-service", "sync-http", True, "Care plan status"),
              dep("analytics-service", "sync-http", True, "Cohort queries"),
              dep("report-generator", "sync-http", False, "Population reports")],
        datastores=[rds("population-health-db", critical=True, restricted=True)],
        features=[{"name": "cohort-builder"}, {"name": "sdoh-analysis"}, {"name": "hedis-measures"}],
        tags={"tier": "2", "domain": "analytics", "phi": "true"}),

    svc("cost-transparency-service", "Cost Transparency Service", "commerce", "commerce@acme.com",
        "prod", 2, "Python 3.12", "fastapi",
        "Commerce", "Member Engagement",
        "Machine-readable files and member cost estimator per CMS price transparency rules.",
        "INTERNAL",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("eligibility-service", "sync-http", True, "Member benefit details"),
              dep("claims-service", "sync-http", False, "Historical cost data"),
              dep("storage-service", "s3", True, "MRF file publication"),
              dep("config-service", "sync-http", False, "Transparency rules")],
        datastores=[rds("cost-db"), s3("mrf-files")],
        features=[{"name": "mrf-generation"}, {"name": "cost-estimator"}, {"name": "aob-calculation"}],
        tags={"tier": "2", "domain": "commerce", "regulatory": "true"}),

    svc("health-record-service", "Health Record Service", "clinical", "clinical@acme.com",
        "prod", 1, "Java 21", "spring-boot",
        "Clinical", "Care Navigation",
        "FHIR R4 clinical data repository and patient record access.",
        "RESTRICTED",
        deps=[dep("auth-service", "sync-http", True, "Token validation"),
              dep("consent-service", "sync-http", True, "Access consent check"),
              dep("document-service", "sync-http", True, "Clinical document storage"),
              dep("audit-log-service", "async-event", True, "Record access audit"),
              dep("integration-hub", "async-event", True, "HL7 ingest")],
        datastores=[rds("fhir-db", critical=True, restricted=True),
                    s3("clinical-documents", restricted=True)],
        features=[{"name": "fhir-r4-api"}, {"name": "ccd-generation"},
                  {"name": "patient-everything"}, {"name": "smart-on-fhir"}],
        tags={"tier": "1", "domain": "clinical", "phi": "true"}),
]


def write_services(services, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    for s in services:
        path = os.path.join(out_dir, f"{s['serviceId']}.json")
        with open(path, "w") as f:
            json.dump(s, f, indent=2)
        print(f"  wrote {path}")
    print(f"\nTotal: {len(services)} files")


if __name__ == "__main__":
    write_services(SERVICES, OUT_DIR)
